create table if not exists public.demo_love_events (
  id bigint generated by default as identity primary key,
  device_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists demo_love_events_device_hash_idx
  on public.demo_love_events (device_hash);

alter table public.demo_love_events enable row level security;

create table if not exists public.demo_love_devices (
  device_hash text primary key,
  created_at timestamptz not null default now()
);

alter table public.demo_love_devices enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demo_love_events'
      and policyname = 'Service role can manage demo love events'
  ) then
    create policy "Service role can manage demo love events"
      on public.demo_love_events
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demo_love_events'
      and policyname = 'Public demo can read love events'
  ) then
    create policy "Public demo can read love events"
      on public.demo_love_events
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demo_love_events'
      and policyname = 'Public demo can add love events'
  ) then
    create policy "Public demo can add love events"
      on public.demo_love_events
      for insert
      to anon
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demo_love_devices'
      and policyname = 'Service role can manage demo love devices'
  ) then
    create policy "Service role can manage demo love devices"
      on public.demo_love_devices
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demo_love_devices'
      and policyname = 'Public demo can read love devices'
  ) then
    create policy "Public demo can read love devices"
      on public.demo_love_devices
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demo_love_devices'
      and policyname = 'Public demo can add love devices'
  ) then
    create policy "Public demo can add love devices"
      on public.demo_love_devices
      for insert
      to anon
      with check (true);
  end if;
end $$;
