create table if not exists public.demo_love_events (
  id bigint generated by default as identity primary key,
  device_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists demo_love_events_device_hash_idx
  on public.demo_love_events (device_hash);

alter table public.demo_love_events enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demo_love_events'
      and policyname = 'Service role can manage demo love events'
  ) then
    create policy "Service role can manage demo love events"
      on public.demo_love_events
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;
